# Generated by Django 3.1.7 on 2022-02-06 03:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_headingarticle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='headingarticle',
            name='article',
        ),
        migrations.AddField(
            model_name='article',
            name='heading',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='article', to='core.headingarticle', verbose_name='Рубрика'),
        ),
    ]
