# Generated by Django 3.1.7 on 2022-02-06 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20220206_0632'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='headingarticle',
            options={'verbose_name': 'Рубрика', 'verbose_name_plural': 'Рубрики'},
        ),
    ]
