# Generated by Django 3.1.7 on 2022-02-06 03:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20220206_0636'),
    ]

    operations = [
        migrations.CreateModel(
            name='Main_Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='articles_image', verbose_name='Главная картинка статьи')),
                ('heading', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articless', to='core.headingarticle', verbose_name='Рубрика')),
            ],
        ),
    ]
