# Generated by Django 3.1.7 on 2022-02-06 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_main_article'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='picture',
            new_name='photos',
        ),
        migrations.DeleteModel(
            name='Main_Article',
        ),
    ]
