# Generated by Django 3.1.7 on 2022-02-06 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20220206_1135'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='photos',
            new_name='picture',
        ),
    ]
