# Generated by Django 3.1.7 on 2022-02-06 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20220206_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='main_article',
            field=models.BooleanField(default=False),
        ),
    ]
