# Generated by Django 3.1.7 on 2022-02-06 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_article_main_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='center_article',
            field=models.BooleanField(default=False),
        ),
    ]
