# Generated by Django 3.1.7 on 2022-02-06 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_article_center_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='right_panel_article',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='article',
            name='main_article',
            field=models.BooleanField(default=False, verbose_name='Главная новость'),
        ),
    ]
