# Generated by Django 3.1.7 on 2022-02-06 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20220206_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='main_article',
            field=models.BooleanField(default=False, verbose_name='Первая новость'),
        ),
        migrations.AlterField(
            model_name='article',
            name='right_panel_article',
            field=models.BooleanField(default=False, verbose_name='Главные новости'),
        ),
    ]
