# Generated by Django 3.1.7 on 2022-02-12 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20220212_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='heading',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='article', to='core.headingarticle', verbose_name='Рубрика'),
        ),
    ]
