# Generated by Django 3.1.7 on 2022-02-23 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20220212_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='text_article',
            field=models.BooleanField(default=False, verbose_name='Текстовые новости'),
        ),
    ]
