# Generated by Django 3.1.7 on 2022-02-27 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_article_text_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='margin_article_text',
            field=models.BooleanField(default=False, verbose_name='Ровнительные новости'),
        ),
    ]
