# Generated by Django 3.1.7 on 2022-03-17 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_carousel'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='carousel_block',
            field=models.BooleanField(default=False, verbose_name='Новости в чёрном блоке'),
        ),
    ]
