# Generated by Django 3.1.7 on 2022-03-19 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_article_carousel_block'),
    ]

    operations = [
        migrations.AddField(
            model_name='carousel',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True, verbose_name='URL'),
        ),
    ]
