# Generated by Django 3.1.7 on 2022-03-19 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_carousel_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carousel',
            old_name='slug',
            new_name='carousel_slug',
        ),
    ]
