# Generated by Django 3.1.7 on 2022-03-19 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_auto_20220319_1337'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carousel',
            old_name='carousel_slug',
            new_name='slug',
        ),
    ]
