# Generated by Django 3.1.7 on 2022-03-19 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_auto_20220319_1348'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carousel',
            old_name='slug',
            new_name='article_slug',
        ),
    ]
