# Generated by Django 3.1.7 on 2022-03-24 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_auto_20220319_1351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='pagination_picture_article',
        ),
        migrations.RemoveField(
            model_name='carousel',
            name='article_slug',
        ),
        migrations.AlterField(
            model_name='article',
            name='pagination_article',
            field=models.BooleanField(default=False, verbose_name='Архивные'),
        ),
    ]
