# Generated by Django 3.1.7 on 2022-03-25 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_auto_20220324_1542'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainArticles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='main_pictures')),
                ('title', models.CharField(max_length=150)),
                ('text', models.TextField()),
            ],
            options={
                'verbose_name': 'Главные новости внутри статей',
                'verbose_name_plural': 'Главные новости внутри статей',
            },
        ),
    ]
