# Generated by Django 3.1.7 on 2022-03-25 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_mainarticles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainarticles',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='main_pictures'),
        ),
    ]
