# Generated by Django 3.1.7 on 2022-03-25 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_auto_20220325_0923'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MainArticles',
        ),
        migrations.AddField(
            model_name='article',
            name='article_page_main',
            field=models.BooleanField(default=False, verbose_name='Новости внутри статей'),
        ),
        migrations.AlterField(
            model_name='article',
            name='carousel_block',
            field=models.BooleanField(default=False, verbose_name='Новости дня'),
        ),
    ]
