# Generated by Django 3.1.7 on 2022-03-28 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_auto_20220325_1133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='article_page_main',
        ),
    ]
