# Generated by Django 3.1.7 on 2022-03-31 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_author_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='user',
            field=models.CharField(max_length=255),
        ),
    ]
