# Generated by Django 3.1.7 on 2022-03-31 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_auto_20220331_0908'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='metades',
            field=models.TextField(blank=True, null=True),
        ),
    ]
