# Generated by Django 3.1.7 on 2022-04-01 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_auto_20220401_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='carousel',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True, verbose_name='URL'),
        ),
    ]
