# Generated by Django 3.1.7 on 2022-04-02 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_remove_carousel_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='carousel_block',
        ),
    ]
