# Generated by Django 3.1.7 on 2022-04-02 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_remove_article_carousel_block'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='margin_article_text',
        ),
    ]
