# Generated by Django 3.1.7 on 2022-05-14 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_remove_article_margin_article_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='tt',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
