# Generated by Django 3.1.7 on 2022-05-14 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_article_tt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='tt',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Подтекст'),
        ),
    ]
